apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: almogo
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true