apiVersion: v1
kind: Service
metadata:
  name: vcita-service
  # namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: vcita-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000